services:
  - type: web
    name: sanidu-whatsapp-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB
        sync: false
      - key: SESSION_ID
        sync: false
      - key: PREFIX
        value: .
      - key: OWNER_NUMBER
        value: 94706075447
      - key: MODE
        value: public
